#!/bin/bash

mkdir -p output
sed -e "s/[(,)]/ /g #" postProcessing/computeForces/500/forces* 1> postProcessing/computeForces/500/forcesCleanOld.txt
sed '1d' postProcessing/computeForces/500/forcesCleanOld.txt > postProcessing/computeForces/500/forcesCleanOld2.txt
tail -n +3 postProcessing/computeForces/500/forcesCleanOld2.txt > output/forcesClean.txt
rm -r postProcessing/computeForces/500/forcesCleanOld*
grep -v '^#' output/forcesClean.txt > output/forcesWS.txt
sed -e 's/\s\+/,/g' output/forcesWS.txt >> output/forces.txt
